name: ${project.name}
main: ${project.groupId}.InventoryRollbackPlus
version: ${project.version}
description: ${project.description}
author: ${project.organization.name}
authors: [${project.organization.name}, danjono]
api-version: 1.13
commands:
  inventoryrollbackplus:
    description: ${project.description}
    usage: /irp <subcommand>
    aliases: [ir, irp, inventoryrollback]
permissions:
  inventoryrollbackplus.*:
    description: Gives access to all InventoryRollbackPlus commands.
    children:
      inventoryrollbackplus.cmd: true
      inventoryrollbackplus.deathsave: true
      inventoryrollbackplus.joinsave: true
      inventoryrollbackplus.leavesave: true
      inventoryrollbackplus.worldchangesave: true
      inventoryrollbackplus.enable: true
      inventoryrollbackplus.disable: true
      inventoryrollbackplus.reload: true
      inventoryrollbackplus.restore: true
      inventoryrollbackplus.forcebackup: true
      inventoryrollbackplus.version: true
      inventoryrollbackplus.help: true
      inventoryrollbackplus.adminalerts: true
    default: op
  inventoryrollbackplus.cmd:
    description: Allows InventoryRollback commands to work.
    default: true
    children:
      inventoryrollback.cmd: true
  inventoryrollbackplus.deathsave:
    description: Player inventories will be saved when they die.
    default: true
    children:
      inventoryrollback.deathsave: true
  inventoryrollbackplus.joinsave:
    description: Player inventories will be saved when the join.
    default: true
    children:
      inventoryrollback.joinsave: true
  inventoryrollbackplus.leavesave:
    description: Player inventories will be saved when they leave.
    default: true
    children:
      inventoryrollback.leavesave: true
  inventoryrollbackplus.worldchangesave:
    description: Player inventories will be saved when they change worlds.
    default: true
    children:
      inventoryrollback.worldchangesave: true
  inventoryrollbackplus.enable:
    description: Grants access to enable the plugin globally.
    default: op
    children:
      inventoryrollback.enable: true
  inventoryrollbackplus.disable:
    description: Grants access to disable the plugin globally.
    default: op
    children:
      inventoryrollback.disable: true
  inventoryrollbackplus.reload:
    description: Grants access to reload the plugin configuration.
    default: op
    children:
      inventoryrollback.reload: true
  inventoryrollbackplus.restore:
    description: Grants access to perform player roll backs.
    default: op
    children:
      inventoryrollback.restore: true
  inventoryrollbackplus.forcebackup:
    description: Forces a backup for an online player.
    default: op
    children:
      inventoryrollback.forcebackup: true
  inventoryrollbackplus.version:
    description: Allows player to see the version the plugin is running on the server.
    default: true
    children:
      inventoryrollback.version: true
  inventoryrollbackplus.adminalerts:
    description: Allows player to receive extra notifications related to the plugin when joining.
    default: op
  inventoryrollbackplus.help:
    description: Get the list of commands and what they do
    default: true
  # ---- LEGACY ----
  inventoryrollback.cmd:
    description: Allows InventoryRollback commands to work.
  inventoryrollback.deathsave:
    description: Player inventories will be saved when they die.
  inventoryrollback.joinsave:
    description: Player inventories will be saved when the join.
  inventoryrollback.leavesave:
    description: Player inventories will be saved when they leave.
  inventoryrollback.worldchangesave:
    description: Player inventories will be saved when they change worlds.
  inventoryrollback.enable:
    description: Grants access to enable the plugin globally.
  inventoryrollback.disable:
    description: Grants access to disable the plugin globally.
  inventoryrollback.reload:
    description: Grants access to reload the plugin configuration.
  inventoryrollback.restore:
    description: Grants access to perform player roll backs.
  inventoryrollback.forcebackup:
    description: Forces a backup for an online player.
  inventoryrollback.version:
    description: Allows player to see the version the plugin is running on the server.